### ISSUE TITLE
Extension won't work

### ISSUE THREAD

**Issue by Mik-813** [poeticAndroid/pretty-gd-vs#1]
"A formatter for GDScript that just works!"
Too bad it doesn't 😂
Seriously though. It infinitely loads, no formmating is fisible

**Comment by poeticAndroid** [comment]
I'm sorry to hear you're having trouble..
Does the extension not load at all, even with all other extensions disabled..?
or is it when formatting a document..? if so, could you post the gdscript you're trying to format..?

**Comment by Mik-813** [comment]
The problem was on my side. I had another fomatter installed which probably conflicted with pretty-gd since after its deinstallation pretty-gd started working.
