### ISSUE TITLE
Format error with large numbers (underscore notation)

### ISSUE THREAD

**Issue by AuraDvin** [poeticAndroid/pretty-gd-vs#2]
When using the notation for large numbers like 10_000_000 (meaning 10000000) the formatter will add a space before the first underscore resulting in Godot Parse errors (Godot 3.5.1, Windows 10, VSC)
Before formatting:
![image](https://user-images.githubusercontent.com/87951242/223458023-b54bf22c-d582-469b-8387-0722401c1ba8.png)
After formatting: 
![image](https://user-images.githubusercontent.com/87951242/223458108-f8db75b6-be8b-4bec-aad2-c36f07dc2dec.png)
![image](https://user-images.githubusercontent.com/87951242/223458181-d09d9ab4-e555-44ad-ad93-4b23bb6a4360.png)

Am I doing something wrong with the formatter, or is this an issue on the extension's end? 

Thanks for all the help!
Regards,
Aura

**Comment by poeticAndroid** [comment]
Thanks for letting me know! It should be fixed now.. :)
