### ISSUE TITLE
Space is Missing for Named Enum Declarations

### ISSUE THREAD

**Issue by michaelschufi** [poeticAndroid/pretty-gd-vs#4]
First of all, thank you! It's great this extension has no dependencies 😅

My report:

```gdscript
enum Direction {
  UP,
  DOWN,
  LEFT,
  RIGHT
}
```

formats to 

```gdscript
enum Direction{
  UP,
  DOWN,
  LEFT,
  RIGHT
}
```
while 

```gdscript
enum {
  UP,
  DOWN,
  LEFT,
  RIGHT
}
```
stays the same.

I propose to add a space between the bracket and the enum name.

**Comment by poeticAndroid** [comment]
This should now be fixed :)
