### ISSUE TITLE
Pretty Please add pretty-gd to open vsx

### ISSUE THREAD

**Issue by lankv2** [poeticAndroid/pretty-gd-vs#5]
I would greatly appreciate it if you could add pretty-gd to open vsx so it can be used on vscodium.

publishing process: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

additional doc: https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md

Thank you.

**Comment by poeticAndroid** [comment]
Here it is: https://open-vsx.org/extension/poeticAndroid/pretty-gd
