### ISSUE TITLE
Extra space added between ! and variable names in conditional statements

### ISSUE THREAD

**Issue by TypicalFooBar** [poeticAndroid/pretty-gd-vs#6]
Hello!

This plugin is wonderful and easy to use, however there is one thing I would like to see tweaked.

Currently, when formatting, spaces will be added between `!` and variable names. Example:

```gdscript
if !some_variable && !some_other_variable:
    pass
```

The above would turn into

```gdscript
if ! some_variable && ! some_other_variable:
    pass
```

I'd either love to see this behavior removed _or_ there be an associated settings file with this extension that let's this behavior be turned on/off depending on the preference of the dev.

Appreciate ya!

**Comment by poeticAndroid** [comment]
This should be fixed now :)
